print(f'{'-=-'*15:^50}')
print(f'{'fistagem supermercado':^50}')
print(f'{'-=-'*15:^50}')
print((f'\033[31mfista com capacidade de 4 itens : '))
print('\033[m')
a = str(input(f'Digite o primeiro item : '))
b = float(input(f'Digite o prço do primeiro item : '))
c = str(input(f'Digite o segundo item : '))
d = float(input(f'Digite o preço do segundo item : '))
e = str(input(f'Digite o terceiro item : '))
f = float(input(f'Digite o preço do terceiro item : '))
g = str(input(f'Digite o quarto item : '))
h = float(input(f'Digite o preço do quarto item : '))
t = (a,b,c,d,e,f,g,h)
for c in range(0,7,2):
    print(f'{t[c]:.<15}{t[c+1]:.>15}')